# Generated by Django 5.2.10 on 2026-01-20 08:12

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id_annee', models.AutoField(primary_key=True, serialize=False)),
                ('debut', models.IntegerField(blank=True, null=True)),
                ('fin', models.IntegerField(blank=True, null=True)),
                ('annee', models.CharField(max_length=20)),
                ('etat_annee', models.CharField(choices=[('En attente', 'En attente'), ('En Cours', 'En Cours'), ('Cloturée', 'Cloturée')], default='En attente', max_length=50)),
                ('date_ouverture', models.DateField()),
                ('date_cloture', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Année_scolaire',
                'db_table': 'annee',
            },
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id_banque', models.AutoField(primary_key=True, serialize=False)),
                ('banque', models.CharField(max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'recouvrment_banque',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id_campus', models.AutoField(primary_key=True, serialize=False)),
                ('campus', models.CharField(max_length=50, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'db_table': 'campus',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('classe', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Classe_cycle',
            fields=[
                ('id_cycle', models.AutoField(primary_key=True, serialize=False)),
                ('cycle', models.CharField(choices=[('Maternelle', 'Maternelle'), ('Fondamentale', 'Fondamentale'), ('Post Fondamentale', 'Post Fondamentale')], max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cycle de Classe',
                'db_table': 'classe_cycle',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id_eleve', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=50)),
                ('etat_civil', models.CharField(blank=True, choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Autres', 'Autres')], default='Célibataire', max_length=50, null=True)),
                ('code_eleve', models.CharField(blank=True, max_length=250, null=True)),
                ('code_annee', models.IntegerField(blank=True, default=0, null=True)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_pere', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('prenom_pere', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('nom_mere', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('prenom_mere', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_parent', models.EmailField(blank=True, max_length=254, null=True)),
                ('password_parent', models.CharField(blank=True, max_length=300, null=True)),
                ('password', models.CharField(blank=True, max_length=300, null=True)),
                ('tutaire', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BI')),
                ('date_naissance', models.DateField(auto_now_add=True)),
                ('naissance_region', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('naissance_pays', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('naissance_province', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('naissance_commune', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('naissance_zone', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('province_actuelle', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('commune_actuelle', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('zone_actuelle', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='logos/eleves/')),
                ('nationalite', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('professionPere', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('professionMere', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('profsion_tutaire', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('IDelivranceLieuEtDate', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('code_secret_parent', models.CharField(blank=True, max_length=250, null=True)),
                ('code_secret_eleve', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'eleve',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id_ecole', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ecole', models.CharField(max_length=250, unique=True)),
                ('sigle', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('domaine', models.CharField(blank=True, max_length=50)),
                ('site', models.URLField(blank=True, max_length=50)),
                ('logo_ecole', models.ImageField(blank=True, null=True, upload_to='logos/ecole/')),
                ('logo_ministere', models.ImageField(blank=True, null=True, upload_to='logos/ministere/')),
                ('siege', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('representant', models.CharField(blank=True, max_length=50)),
                ('b_postale', models.CharField(blank=True, max_length=50)),
                ('emplacement', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'ecole',
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id_periode', models.AutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P8', 'P8'), ('P9', 'P9')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'periode',
                'db_table': 'periode',
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id_trimestre', models.AutoField(primary_key=True, serialize=False)),
                ('trimestre', models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3'), ('Trimestre 4', 'Trimestre 4'), ('Trimestre 5', 'Trimestre 5'), ('Trimestre 6', 'Trimestre 6'), ('Trimestre 7', 'Trimestre 7')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trimestre',
                'db_table': 'Trimestre',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id_variable', models.AutoField(primary_key=True, serialize=False)),
                ('variable', models.CharField(max_length=200)),
                ('estObligatoire', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'recouvrment_variable',
            },
        ),
        migrations.CreateModel(
            name='VariableCategorie',
            fields=[
                ('id_variable_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'recouvrment_variable_categorie',
            },
        ),
        migrations.CreateModel(
            name='Classe_cycle_actif',
            fields=[
                ('id_cycle_actif', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('nbre_classe_par_cycle_actif', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('ordre', models.PositiveIntegerField(blank=True, null=True)),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_cycle')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
            ],
            options={
                'verbose_name': 'Cycle Actif',
                'db_table': 'classe_cycle_actif',
            },
        ),
        migrations.CreateModel(
            name='Classe_active',
            fields=[
                ('id_classe_active', models.AutoField(primary_key=True, serialize=False)),
                ('groupe', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True)),
                ('isTerminale', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('ordre', models.PositiveIntegerField(blank=True, null=True)),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_cycle_actif')),
            ],
            options={
                'verbose_name': 'Classe Active',
                'db_table': 'classe_active',
            },
        ),
        migrations.CreateModel(
            name='Annee_trimestre',
            fields=[
                ('id_trimestre', models.AutoField(primary_key=True, serialize=False)),
                ('debut', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('etat_trimestre', models.CharField(choices=[('En attente', 'En attente'), ('En Cours', 'En Cours'), ('Cloturée', 'Cloturée')], default='En attente', max_length=50)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_cycle_actif')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.trimestre')),
            ],
            options={
                'verbose_name': 'Trimestre_AnnéeScolaire',
                'db_table': 'annee_trimestre',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id_compte', models.AutoField(primary_key=True, serialize=False)),
                ('compte', models.CharField(max_length=200)),
                ('id_banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.banque')),
            ],
            options={
                'db_table': 'recouvrment_compte',
            },
        ),
        migrations.CreateModel(
            name='Eleve_inscription',
            fields=[
                ('id_inscription', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('redoublement', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('isDelegue', models.BooleanField(default=False)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_active')),
                ('id_classe_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_cycle_actif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.eleve')),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee_trimestre')),
            ],
            options={
                'db_table': 'eleve_inscription',
            },
        ),
        migrations.CreateModel(
            name='Annee_periode',
            fields=[
                ('id_periode', models.AutoField(primary_key=True, serialize=False)),
                ('debut', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('etat_periode', models.CharField(choices=[('En attente', 'En attente'), ('En Cours', 'En Cours'), ('Cloturée', 'Cloturée')], default='En attente', max_length=50)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_trimestre_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee_trimestre')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_cycle_actif')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.periode')),
            ],
            options={
                'verbose_name': 'Période_AnnéeScolaire',
                'db_table': 'annee_periode',
            },
        ),
        migrations.AddField(
            model_name='periode',
            name='id_trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.trimestre'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.PositiveIntegerField(default=0)),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('date_paie', models.DateField()),
                ('bordereau', models.ImageField(blank=True, null=True, upload_to='invoices/')),
                ('status', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.banque')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
                ('id_classe_active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_active')),
                ('id_compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.compte')),
                ('id_cycle_actif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_cycle_actif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.eleve')),
                ('id_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.variable')),
            ],
            options={
                'db_table': 'recouvrment_paiement',
            },
        ),
        migrations.CreateModel(
            name='Eleve_reduction_prix',
            fields=[
                ('id_reduction_prix', models.AutoField(primary_key=True, serialize=False)),
                ('pourcentage', models.PositiveIntegerField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
                ('id_classe_active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_active')),
                ('id_cycle_actif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_cycle_actif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.eleve')),
                ('id_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.variable')),
            ],
            options={
                'db_table': 'recouvrment_reduction_prix',
            },
        ),
        migrations.AddField(
            model_name='variable',
            name='id_variable_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.variablecategorie'),
        ),
        migrations.CreateModel(
            name='VariableDatebutoire',
            fields=[
                ('id_datebutoire', models.AutoField(primary_key=True, serialize=False)),
                ('date_butoire', models.DateField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
                ('id_classe_active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_active')),
                ('id_cycle_actif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_cycle_actif')),
                ('id_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.variable')),
            ],
            options={
                'db_table': 'recouvrment_variable_datebutoire',
            },
        ),
        migrations.CreateModel(
            name='VariableDerogation',
            fields=[
                ('id_derogation', models.AutoField(primary_key=True, serialize=False)),
                ('date_derogation', models.DateField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
                ('id_classe_active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_active')),
                ('id_cycle_actif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_cycle_actif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.eleve')),
                ('id_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.variable')),
            ],
            options={
                'db_table': 'recouvrment_variable_derogation',
            },
        ),
        migrations.CreateModel(
            name='VariablePrix',
            fields=[
                ('id_prix', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.PositiveIntegerField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
                ('id_classe_active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_active')),
                ('id_cycle_actif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.classe_cycle_actif')),
                ('id_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.variable')),
            ],
            options={
                'db_table': 'recouvrment_variable_prix',
            },
        ),
    ]
