# Generated by Django 5.2.10 on 2026-01-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableprix',
            name='id_annee_trimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.annee_trimestre'),
            preserve_default=False,
        ),
    ]
