# Generated by Django 5.2.10 on 2026-01-28 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_variableprix_id_annee_trimestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaliteConfig',
            fields=[
                ('id_penalite_regle', models.AutoField(primary_key=True, serialize=False)),
                ('type_penalite', models.CharField(choices=[('FORFAIT', 'Forfait'), ('POURCENTAGE', 'Pourcentage')], max_length=20)),
                ('valeur', models.FloatField()),
                ('plafond', models.PositiveIntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('id_annee_trimestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.annee_trimestre')),
                ('id_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
                ('id_classe_active', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.classe_active')),
                ('id_cycle_actif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.classe_cycle_actif')),
                ('id_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.variable')),
            ],
            options={
                'db_table': 'recouvrement_penalite_regle',
                'unique_together': {('id_variable', 'id_annee_trimestre', 'id_classe_active', 'id_cycle_actif', 'id_campus')},
            },
        ),
    ]
