# Generated by Django 5.2.10 on 2026-02-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_variableprix_id_annee_trimestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieOperation',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('type_operation', models.CharField(choices=[('ENTREE', "Entrée d'argent"), ('SORTIE', "Sortie d'argent")], max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'recouvrement_categorie_operation',
                'ordering': ['type_operation', 'nom'],
                'unique_together': {('type_operation', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='OperationCaisse',
            fields=[
                ('id_operation', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.IntegerField(verbose_name='Montant')),
                ('date_operation', models.DateField(verbose_name='Date')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('source_beneficiaire', models.CharField(blank=True, help_text='Source (entrée) ou bénéficiaire (sortie)', max_length=200, null=True)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='app.categorieoperation')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'db_table': 'recouvrement_operation',
                'ordering': ['-date_operation', '-date_enregistrement'],
                'indexes': [models.Index(fields=['id_annee', 'id_campus', 'date_operation'], name='recouvremen_id_anne_41c427_idx')],
            },
        ),
        migrations.CreateModel(
            name='PenaliteConfig',
            fields=[
                ('id_penalite_regle', models.AutoField(primary_key=True, serialize=False)),
                ('type_penalite', models.CharField(choices=[('FORFAIT', 'Forfait'), ('POURCENTAGE', 'Pourcentage')], max_length=20)),
                ('valeur', models.FloatField()),
                ('plafond', models.PositiveIntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annee')),
                ('id_annee_trimestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.annee_trimestre')),
                ('id_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.campus')),
                ('id_classe_active', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.classe_active')),
                ('id_cycle_actif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.classe_cycle_actif')),
                ('id_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.variable')),
            ],
            options={
                'db_table': 'recouvrement_penalite',
                'unique_together': {('id_variable', 'id_annee_trimestre', 'id_classe_active', 'id_cycle_actif', 'id_campus')},
            },
        ),
    ]
