# Generated by Django 5.2.10 on 2026-01-28 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_penaliteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaliteconfig',
            name='id_annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.annee'),
            preserve_default=False,
        ),
    ]
