
from django.contrib import admin
from django.urls import path
from app import views

# RECOUVREMENT :
urlpatterns =[
   path('categorie_variable/', views.ajouter_categorie_variable, name='categorie_variable'),
   path('create_variable_frais/', views.ajouter_variable, name='create_variable_frais'),
   path('update_categorie/<int:categorie_id>/', views.update_categorie, name='update_categorie'),
   path('update_variable/<int:variable_id>/', views.update_variable, name='update_variable'),
   path('get_categories/', views.get_categories, name='get_categories'),
   path('create_banque/', views.ajouter_banque_epargne, name='create_banque'),
   path('create_compte/', views.ajouter_compte_epargne, name='create_compte'),
   path('update_banque/<int:banque_id>/', views.update_banque, name='update_banque'),
   path('get_banques/', views.get_banques, name='get_banques'),
   path('update_compte/<int:compte_id>/', views.update_compte, name='update_compte'),
   path('create_variable_prix', views.ajouter_variable_prix, name='create_variable_prix'),
   path('create_variable_reduction', views.ajouter_reduction_for_pupil, name='create_variable_reduction'),
   path('create_derogation_classe', views.ajouter_variable_derogation, name='create_derogation_classe'),
   path('store_annee_session/', views.store_annee_session, name='store_annee_session'),
   path('get_classes_actives/<int:annee_id>/', views.get_classes_actives, name='get_classes_actives'),
   path('get_classes_actives_with_paie/<int:annee_id>/', views.get_classes_actives_avec_paiement, name='get_classes_actives_with_paie'),
   path('save_variable_prix/', views.save_variable_prix, name='save_variable_prix'),
   path('save_variable_derogation/', views.save_variable_derogation, name='save_variable_derogation'),
   path('save_variable_reduction/', views.save_variable_reduction, name='save_variable_reduction'),
   path('ajouter_date_butoire/', views.ajouter_date_butoire_for_anyclass, name='ajouter_date_butoire'),
   path('save_date_butoire/', views.save_variable_date_butoire, name='save_date_butoire'),
   path('ajouter_paiement/', views.add_paiement_for_anyclass, name='ajouter_paiement'),
   path('get_comptes_banque/<int:id_banque>/', views.get_comptes_banque, name='get_comptes_banque'),
   path('save_paiement/', views.save_paiement, name='save_paiement'),
   path('afficher_paiement_submitted/', views.get_all_paiement_soumises, name='afficher_paiement_submitted'),
   path('paiement_valider/', views.get_all_paiement_soumises, name='paiement_valider'),
   path('get_paiements_submitted/', views.get_paiements_submitted, name='get_paiements_submitted'),
   path('get_paiements_validated/', views.get_paiements_validated, name='get_paiements_validated'),
   path('update_paiement_field/', views.update_paiement_field, name='update_paiement_field'),
   path('generate_invoice/<int:id_paiement>/', views.generate_invoice, name='generate_invoice'),
   path('generate_fiche_paie_classe/', views.generate_fiche_paie_classe, name='generate_fiche_paie_classe'),
   path('get_pupils_registred_classe/', views.get_pupils_registred_classe, name='get_pupils_registred_classe'),
   path('get_variables_restant_a_payer/',views.get_variables_restant_a_payer,name='get_variables_restant_a_payer'),
   path('get_trimestres_by_classe_active/', views.get_trimestres_by_classe_active, name='get_trimestres_by_classe_active'),
   path('get-variables-by-trimestre/',views.get_variables_by_trimestre,name='get_variables_by_trimestre'),
   path('generate_fiche_paie_eleve/', views.generate_fiche_paie_eleve, name='generate_fiche_paie_eleve'),
   path('get_eleves_classe/', views.get_eleves_classe, name='get_eleves_classe'),
   path('get_paiements_eleve/', views.get_paiements_eleve, name='get_paiements_eleve'),
   path('ajouter_penalite/', views.ajouter_penalite, name='ajouter_penalite'),
   path('save_penalite/', views.save_penalite, name='save_penalite'),
   path('get_penalites/', views.get_penalites, name='get_penalites'),
   path('eleves_penalite/', views.eleves_penalite, name='eleves_penalite'),
   path('eleves_en_penalite/', views.eleves_en_penalite, name='eleves_en_penalite'),
   path('toggle_penalite_actif/', views.toggle_penalite_actif, name='toggle_penalite_actif'),
   path('historique/', views.historique, name='historique'),
   path('historique_financier/', views.historique_financier, name='historique_financier'),
   path('generate_historique_pdf/', views.generate_historique_pdf, name='generate_historique_pdf'),
   path('dettes_anterieures/', views.dette_anterieures, name='dettes_anterieures'),
   path('eleves_en_dette/', views.eleves_en_dette, name='eleves_en_dette'),
   path('generate_dette_pdf/', views.generate_dette_pdf, name='generate_dette_pdf'),
   path('get_paiements_for_add_page/',views.get_paiements_for_add_page, name='get_paiements_for_add_page'),
   path('delete_paiement/<int:id_paiement>/', views.delete_paiement, name='delete_paiement'),
   path('paiement/update/<int:id_paiement>/', views.update_paiement, name='update_paiement'),
   path('generate_facture_paiement/', views.generate_facture_paiement, name='generate_facture_paiement'),
   path('', views.dashboard, name='dashboard'),
   path('dashboard-data/', views.dashboard_data, name='dashboard_data'),
   path('dashboard-details/', views.dashboard_details, name='dashboard_details'),
   path('suivi-reduction-derogation/',views.suivi_reduction_derogation,name='suivi_reduction_derogation'),
   path('suivi-reduction-derogation-data/',views.suivi_reduction_derogation_data,name='suivi_reduction_derogation-data'),
   path('suivi-reduction-update/<int:id>/', views.suivi_reduction_update, name='suivi_reduction_update'),
   path('suivi-derogation-update/<int:id>/', views.suivi_derogation_update, name='suivi_derogation_update'),
   path('get_date_butoires/',views.get_dates_butoire,name='get_date_butoires'),
   path('update_date_butoire/<int:id>/', views.update_date_butoire, name='update_date_butoire'),
   path('situation_journaliere/', views.situation_journaliere, name='situation_journaliere'),
   path('situation_journaliere_data/', views.situation_journaliere_data, name='situation_journaliere_data'),
   path('generate_situation_pdf/', views.generate_situation_pdf, name='generate_situation_pdf'),
   path('update-variable-obligatoire/', views.update_variable_obligatoire, name='update-variable-obligatoire'),
   path('export-dashboard-pdf/', views.export_dashboard_pdf, name='export-dashboard-pdf'),
   path('export-dashboard-excel/',views.export_dashboard_excel,name='export_dashboard_excel'),
   path('generate_historique_excel/', views.generate_historique_excel, name='generate_historique_excel'),
   path('generate_dette_excel/', views.generate_dette_excel, name='generate_dette_excel'),
   path('generate_situation_excel/',views.generate_situation_excel,name='generate_situation_excel'),
   path('rapport_paiement/',views.rapport_paiement,name='rapport_paiement'),
   path("rapport-paiements/", views.rapport_paiements, name="rapport_paiements"),
   path('liste_categories/', views.liste_categories, name='liste_categories'),
   path('liste_operations/', views.liste_operations, name='liste_operations'),

   path('save_categorie_operation/', views.save_categorie_operation, name='save_categorie_operation'),
   path('get_annees_actives/', views.get_annees_actives, name='get_annees_actives'),
   path('get_campus_actifs/', views.get_campus_actifs, name='get_campus_actifs'),
   path('get_categories_filtrees/', views.get_categories_filtrees, name='get_categories_filtrees'),
   path('get_categories_operations/', views.get_categories_operations, name='get_categories_operations'),

   path('save_operation_caisse/', views.save_operation_caisse, name='save_operation_caisse'),
   path('get_operations_caisse/', views.get_operations_caisse, name='get_operations_caisse'),
   path('get_categories_by_filters/', views.get_categories_by_filters, name='get_categories_by_filters'),
   path('delete_operation/<int:id_operation>/', views.delete_operation, name='delete_operation'),

   
]